[project]
name = "claude-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Manmohan Bohara", email = "manmohan.bohara@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "anthropic>=0.122.0",
    "python-dotenv>=1.2.2",
]

[project.scripts]
claude-project = "claude_project:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "ipykernel>=7.3.0",
    "jupyter>=1.1.1",
]
